// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjKgq-Kq02meHFUyTzRdiKX_ieWi1h-fQ',
    appId: '1:539768291770:web:e7a7d6cb59aa39d06f5d83',
    messagingSenderId: '539768291770',
    projectId: 'bayankonek2',
    authDomain: 'bayankonek2.firebaseapp.com',
    storageBucket: 'bayankonek2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK3eKNUIgqGm0PGqRcgY5UIrXtSahNb1g',
    appId: '1:539768291770:android:d79ba9f66aec6d206f5d83',
    messagingSenderId: '539768291770',
    projectId: 'bayankonek2',
    storageBucket: 'bayankonek2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq_3gRLg549ydMiL8SuZjToDnNiU9uFcc',
    appId: '1:539768291770:ios:6377f8de57306fa06f5d83',
    messagingSenderId: '539768291770',
    projectId: 'bayankonek2',
    storageBucket: 'bayankonek2.firebasestorage.app',
    iosBundleId: 'com.example.bayankonek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq_3gRLg549ydMiL8SuZjToDnNiU9uFcc',
    appId: '1:539768291770:ios:6377f8de57306fa06f5d83',
    messagingSenderId: '539768291770',
    projectId: 'bayankonek2',
    storageBucket: 'bayankonek2.firebasestorage.app',
    iosBundleId: 'com.example.bayankonek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjKgq-Kq02meHFUyTzRdiKX_ieWi1h-fQ',
    appId: '1:539768291770:web:2de2b92efbac09a96f5d83',
    messagingSenderId: '539768291770',
    projectId: 'bayankonek2',
    authDomain: 'bayankonek2.firebaseapp.com',
    storageBucket: 'bayankonek2.firebasestorage.app',
  );
}
